# -*- coding: utf-8 -*-
"""build_hebrew.py -- the 22 Hebrew letters (and their five final forms) as an
engine letter table, for the Introduction mode's Hebrew lessons and the golem.

    python v2/data/build_hebrew.py            # writes v2/data/hebrew.json
    python v2/data/build_hebrew.py --verify   # checks the table against the source

Source of the evidence layer: ../GoldenDawnBlocks/data/letters.json, itself
generated by that project's build_letters.py from the Sefer Yetsirah's own
3/7/12 division and the diagram manuscript Segol (2012) translates. This script
does not re-derive any of that; it carries it across and adds only what the
Arabic engine needs to run these letters at all:

  * `abjad`   = the gematria value (the engine's num() reads value or abjad)
  * `class`   = the SY class (mother / double / simple), which no shipped ruleset
                counts for luminosity -- so power rules fall to their floor
  * `grammar.connects_forward` = true for every ordinary letter: Hebrew script
                does not join on the page, but a written word is one body here as
                in Arabic, because "combined one with another" is what the SY says
                the letters do
  * the five FINAL FORMS as their own entries, with SEVER: a final form is
                Hebrew's visible word-end, so a body ends where one stands.
                GoldenDawnBlocks calls this SEAL. INTERPRETATION, ours, and said
                so in the table's own note.

No other primitive is given to a Hebrew letter. The mothers' elements, the
doubles' aspects and the simples' faculties are carried in `sy` for the lessons
to show, not for the engine to act on -- what a Hebrew letter DOES as a block is
not yet derived, and the Introduction says so rather than inventing it.
"""
from __future__ import annotations
import io, json, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent.parent / 'GoldenDawnBlocks' / 'data' / 'letters.json'
OUT = HERE / 'hebrew.json'

FINALS = {'כ': 'ך', 'מ': 'ם', 'נ': 'ן', 'פ': 'ף', 'צ': 'ץ'}

def build():
    src = json.loads(io.open(SRC, encoding='utf-8').read())
    letters = []
    for l in src['letters']:
        entry = {
            'glyph': l['glyph'], 'name': l['name'], 'translit': l['translit'],
            'abjad': l['value'], 'value': l['value'],
            'class': l['kind'], 'kind': l['kind'],
            'sy': l['sy'],
            'grammar': {'connects_forward': True, 'final_of': None},
            'facts': {**l['facts'], 'final': False, 'has_final': bool(l['facts'].get('final')), 'final_form': FINALS.get(l['glyph'])},
            'registers': l['registers'],
            'primitives': [],
            'note': f"{l['name']}, gematria {l['value']}, a {l['kind']} letter of the Sefer Yetsirah.",
        }
        letters.append(entry)
        if l['glyph'] in FINALS:
            letters.append({
                'glyph': FINALS[l['glyph']], 'name': f"{l['name']} (final)", 'translit': l['translit'],
                'abjad': l['value'], 'value': l['value'],
                'class': l['kind'], 'kind': l['kind'], 'sy': l['sy'],
                'grammar': {'connects_forward': False, 'final_of': l['glyph']},
                'facts': {**l['facts'], 'final': True, 'has_final': False, 'final_form': None},
                'registers': {'mental': l['registers']['mental'], 'spoken': l['registers']['spoken'], 'written': FINALS[l['glyph']]},
                'primitives': [{'op': 'SEVER', 'n': True, 'from': 'a final form: the letter that ends a word on the page'}],
                'note': f"The final form of {l['name']}: written at the end of a word, and only there. A body of letters ends where it stands.",
            })
    return {
        '_note': ("The Hebrew letters as an engine letter table: 22 letters and their five final forms. "
                  "EVIDENCE carried from ../GoldenDawnBlocks/data/letters.json (the Sefer Yetsirah's 3/7/12 division, "
                  "the mothers' elements, the doubles' two aspects, the simples' faculties, gematria). ADDED here, and "
                  "ours: every ordinary letter joins forward (a written word is one body), and the five final forms SEVER "
                  "(a body ends where a final form stands -- Hebrew's visible word-end; GoldenDawnBlocks calls it SEAL). "
                  "No other primitive is given to a Hebrew letter: what these letters do as blocks is not yet derived."),
        'sources': src.get('sources', []),
        'divisions': src.get('divisions', {}),
        'interpretation': {
            'connects_forward': 'INTERPRETATION: Hebrew script does not join on the page; the bodies here follow the SY\'s "combined one with another", not the ductus.',
            'finals_sever': 'INTERPRETATION: the final form is the word-end made visible, so it ends a body. Derived from the page, like the Arabic non-connecting letters; the mapping to SEVER is ours.',
        },
        'letters': letters,
    }

def verify(data):
    src = json.loads(io.open(SRC, encoding='utf-8').read())
    base = [l for l in data['letters'] if not l['facts'].get('final')]
    finals = [l for l in data['letters'] if l['facts'].get('final')]
    assert len(base) == 22, len(base)
    assert len(finals) == 5, len(finals)
    assert [l['glyph'] for l in base] == [l['glyph'] for l in src['letters']]
    assert [l['value'] for l in base] == [l['value'] for l in src['letters']]
    kinds = {k: sum(1 for l in base if l['kind'] == k) for k in ('mother', 'double', 'simple')}
    assert kinds == {'mother': 3, 'double': 7, 'simple': 12}, kinds
    assert all(l['primitives'] == [] for l in base)
    assert all(l['primitives'][0]['op'] == 'SEVER' and not l['grammar']['connects_forward'] for l in finals)
    assert all(l['grammar']['connects_forward'] for l in base)
    return f"22 letters + 5 finals; 3/7/12 = {kinds}; finals SEVER, the rest join; values match the source"

if __name__ == '__main__':
    data = build()
    if '--verify' in sys.argv:
        print('hebrew.json --verify:', verify(data))
    else:
        io.open(OUT, 'w', encoding='utf-8').write(json.dumps(data, ensure_ascii=False, indent=1) + '\n')
        print('wrote', OUT, '--', verify(data))
