#!/usr/bin/env python3
# export_game.py — compile scenes + the artifacts they rest on into game/content.js.
# Refuses to export if the artifact build or the narrative linter fails: nothing reaches the game
# that has not passed provenance and lint.
#
#   python scripts/export_game.py
import io, json, os, subprocess, sys
from narrative_lib import ROOT, load_artifacts, load_scenes, first_scene

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
OUT = os.path.join(ROOT, "game", "content.js")


def gate():
    for script in ("build_artifacts.py", "lint_scenes.py"):
        r = subprocess.run([sys.executable, os.path.join(ROOT, "scripts", script)], capture_output=True, text=True, encoding="utf-8")
        print(r.stdout.strip().splitlines()[-1] if r.stdout.strip() else script)
        if r.returncode:
            print(r.stdout)
            sys.exit(f"export refused: {script} failed")


def refs_of(a):
    return (a.get("supported_by", []) + a.get("cites", []) + a.get("observed_facts", []) + a.get("claims", [])
            + a.get("counterevidence", []) + [b["evidence"] for b in a.get("bearings", [])]
            + [c for pr in a.get("proponents", []) for c in pr.get("cites", [])])


def main():
    gate()
    scenes, arts = load_scenes(), load_artifacts()
    keep, stack = {}, []
    for s in scenes.values():
        stack += s["situation"]["based_on"] + [i["claim"] for i in s["invariants"]] + [r for c in s["choices"] for r in c.get("based_on", [])] \
            + [ref for r in s.get("rulings") or [] for ref in r["based_on"]] \
            + [o["hypothesis"] for o in (s.get("commitment") or {}).get("options", [])] \
            + [ref for slot in (s.get("composer") or {}).get("slots", []) for o in slot["options"] for ref in o["based_on"]] \
            + ([s["composer"]["work"]] if s.get("composer") else []) + (s.get("sorter") or {}).get("based_on", [])
    while stack:
        aid = stack.pop()
        if aid in keep or aid not in arts:
            continue
        a = arts[aid]
        keep[aid] = a
        stack += refs_of(a)
    for a in keep.values():
        if a["type"] == "evidence":
            a.pop("read_by", None)
    models = {aid: a for aid, a in arts.items() if a["type"] == "biographical_model"}
    hypotheses = {aid: a for aid, a in keep.items() if a["type"] == "hypothesis"}
    # the court board's names: every institution, kept whole (the board shows who has moved)
    institutions = {aid: a for aid, a in arts.items() if a["type"] == "institution"}
    for aid in institutions:
        keep.setdefault(aid, institutions[aid])
        for r in institutions[aid].get("supported_by", []):
            if r in arts:
                keep.setdefault(r, arts[r])
    content = {"start": first_scene(scenes), "scenes": scenes, "artifacts": keep, "models": models,
               "hypotheses": hypotheses, "institutions": institutions}
    io.open(OUT, "w", encoding="utf-8").write("// generated by scripts/export_game.py — do not edit\nwindow.CONTENT = "
                                              + json.dumps(content, ensure_ascii=False, indent=1) + ";\n")
    print(f"exported {len(scenes)} scenes, {len(keep)} artifacts, {len(hypotheses)} hypotheses, {len(institutions)} institutions -> game/content.js")


if __name__ == "__main__":
    main()
