#!/usr/bin/env python3
# render_docs.py — docs/BIOGRAPHY.md and docs/OEUVRE.md, generated from the artifacts (never hand-edited).
#
#   python scripts/render_docs.py
import io, os, sys
from narrative_lib import ROOT, load_artifacts

sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def key(e):
    d = e["date"].get("start", "")
    return (d + "-00-00")[:10] if d else "9999"


def pages(arts, ids):
    out = []
    for i in ids:
        ev = arts.get(i)
        if ev and ev["type"] == "evidence":
            c = ev["citation"]
            out.append(f"p.{c.get('printed_page') or '?'}")
    return ", ".join(dict.fromkeys(out))


def biography(arts):
    events = sorted((a for a in arts.values() if a["type"] == "event"), key=key)
    L = ["---", "title: Ibn Turka — the life as data", "description: Generated from research/artifacts (events + claims). Do not edit.", "---", "",
         "# The life, as the sources give it", "",
         "Generated by `scripts/render_docs.py` from the `event` artifacts, which cite claims and evidence in Melvin-Koushki's",
         "2012 dissertation (Timeline A.1 and Chapter 1). **The date_kind is part of the fact**: `attested` and `colophon` are",
         "as the dissertation gives them (a colophon date may record copying, not composition); `conjectured` and `inferred` are",
         "his own hedges (\"c.\", \"(?)\", \"presumably\"); `context` is Timurid history that bears on him. **Fixed points** are external",
         "events the player cannot prevent.", "",
         "| date | what | how known | fixed | dissertation page |", "|---|---|---|---|---|"]
    for e in events:
        d = e["date"]
        when = d.get("start", "")
        if d.get("end") and d["end"] != d.get("start"):
            when += "–" + d["end"]
        if d.get("hijri"):
            when += f" (AH {d['hijri']})"
        cl = [arts[c] for c in e["claims"] if c in arts]
        ev = [x for c in cl for x in c.get("supported_by", [])]
        L.append(f"| {when} | {e['description']} | {d.get('date_kind', '')} | {'FIXED' if e.get('fixed_point') else ''} | {pages(arts, ev)} |")
    n = len(events)
    L += ["", f"{n} events. Claims behind them are in `research/artifacts/claims/`; discrepancies the researchers flagged are in `research/notes/`."]
    return "\n".join(L) + "\n"


def oeuvre(arts):
    works = sorted((a for a in arts.values() if a["type"] == "work"), key=lambda w: (w.get("date", {}).get("ce", "9999") or "9999", w["id"]))
    L = ["---", "title: Ibn Turka — the oeuvre", "description: Generated from research/artifacts/works. Do not edit.", "---", "",
         "# The works, dated only as far as the sources allow", "",
         "Generated by `scripts/render_docs.py`. **`date_kind` is strict**: `composition` only where the dissertation says composed;",
         "`transcription` where the only date is a copy date (MK: a colophon in MS Majlis 10196 may record copying, and about",
         "two-thirds of the preserved works were copied in 1425–27, perhaps as evidence in his defence); `conjectured` and `unknown`",
         "as they say.", "",
         "| work | language | date | date_kind | for / addressee | MS Majlis 10196 folios |", "|---|---|---|---|---|---|"]
    for w in works:
        date = (w.get("date") or {}).get("ce", "") or ""
        L.append(f"| {w['title']} | {w['language']} | {date} | {w['date_kind']} | {w.get('addressee', '')} | {w.get('majlis_folios', '')} |")
    L += ["", f"{len(works)} works (the dissertation counts 44 or 45, plus one divan, one ijāza and the letters)."]
    return "\n".join(L) + "\n"


def main():
    arts = load_artifacts()
    for name, fn in (("BIOGRAPHY.md", biography), ("OEUVRE.md", oeuvre)):
        with io.open(os.path.join(ROOT, "docs", name), "w", encoding="utf-8") as f:
            f.write(fn(arts))
        print("wrote docs/" + name)


if __name__ == "__main__":
    main()
